### ISSUE TITLE
Adding Interaction Style?

### ISSUE THREAD

**Issue by thedevelopnik** [Catalysts/structurizr-extensions#10]
Hello! First, want to compliment you on both of these extensions. We are converting to the Kotlin one right now, and while we're not using the SpringBoot one it gave us a model for how we could structure our code into classes per software system.

For the Kotlin extension, both the `uses` and `usedBy` methods ignore the InteractionStyle argument accepted by the standard Structurizr `uses` method. We make extensive use of this in our Structurizr code. Would you be open to a PR that adds that?

**Comment by klu2** [comment]
Sure, go ahead

**Comment by Exordian** [comment]
included in version 1.3.0

thanks for the PR !
