### ISSUE TITLE
Consider grouping workspace related config in `structurizr.workspace`

### ISSUE THREAD

**Issue by snicoll** [Catalysts/structurizr-extensions#2]
There are a bunch of keys that seem to be related to the concept of Workspace. To make that explicit, perhaps it would be better to group them in a sub-namespace (i.e a `public static class Workspace` nested class). 

That way they'll be grouped in `structurizr.workspace` rather that being flat at the root. This will also improve readability of the description (as the context clearly tells it is related to the workspace).

**Comment by klu2** [comment]
fixed with https://github.com/Catalysts/structurizr-extensions/commit/ee297d612b3ac3696676abff53a34215b4a63c69
