### ISSUE TITLE
Architecture is more a sample than a test

### ISSUE THREAD

**Issue by snicoll** [Catalysts/structurizr-extensions#3]
I find it weird to have a `SpringBootApplication` (so with component scan enabled) that runs in the same package area than the auto-configuration. 

It looks more like a sample than an actual test to me so perhaps it could be moved to a regular sample instead?

**Comment by klu2** [comment]
agree, and with https://github.com/Catalysts/cat-boot-structurizr-sample I already have that dedicated sample application.

will remove that code and think of some useful real unit tests

**Comment by klu2** [comment]
fixed with https://github.com/Catalysts/structurizr-extensions/commit/d796c5c4c8b19fb55826e6e600db9dc1ccbde98d
